# 시험 기본 정보
exam_title: "2024년 1학기 중간고사 - 컴퓨터과학개론"
total_points: 100
exam_duration: "90분"
exam_date: "2024-05-28"

# 출제 문제들
questions:
  - question_number: 1
    question: "알고리즘의 시간복잡도와 공간복잡도에 대해 설명하고, Big-O 표기법의 의미와 예시를 들어 설명하시오."
    points: 25
    type: "서술형"
    sample_answer: |
      시간복잡도는 알고리즘 실행에 필요한 시간의 양을, 공간복잡도는 메모리 사용량을 나타낸다.
      Big-O 표기법은 최악의 경우 성능을 나타내며, O(1), O(n), O(n²) 등으로 표현한다.
      예시: 선형 탐색은 O(n), 이진 탐색은 O(log n)의 시간복잡도를 가진다.
    keywords: ["시간복잡도", "공간복잡도", "Big-O", "최악의 경우", "예시"]

  - question_number: 2
    question: "자료구조 중 스택(Stack)과 큐(Queue)의 차이점을 설명하고, 각각의 실제 사용 예시를 들어보시오."
    points: 25
    type: "서술형"
    sample_answer: |
      스택은 LIFO(Last In First Out) 구조로 가장 나중에 들어간 데이터가 먼저 나온다.
      큐는 FIFO(First In First Out) 구조로 먼저 들어간 데이터가 먼저 나온다.
      스택 예시: 함수 호출 스택, 브라우저 뒤로가기
      큐 예시: 프린터 대기열, CPU 스케줄링
    keywords: ["LIFO", "FIFO", "스택", "큐", "실제 예시"]

  - question_number: 3
    question: "객체지향 프로그래밍의 4대 특징을 설명하고, 각각에 대한 간단한 예시를 제시하시오."
    points: 30
    type: "서술형"
    sample_answer: |
      1. 캡슐화: 데이터와 메서드를 하나로 묶고 외부 접근을 제한
      2. 상속: 기존 클래스의 속성과 메서드를 새로운 클래스가 물려받음
      3. 다형성: 같은 인터페이스로 다른 동작을 수행
      4. 추상화: 복잡한 구현을 숨기고 필요한 기능만 노출
    keywords: ["캡슐화", "상속", "다형성", "추상화", "클래스"]

  - question_number: 4
    question: "데이터베이스의 정규화가 필요한 이유와 1차, 2차, 3차 정규화에 대해 간략히 설명하시오."
    points: 20
    type: "서술형"
    sample_answer: |
      정규화는 데이터 중복을 제거하고 무결성을 보장하기 위해 필요하다.
      1차 정규화: 원자값만 가지도록 함 (중복 그룹 제거)
      2차 정규화: 부분 함수 종속성 제거
      3차 정규화: 이행 함수 종속성 제거
    keywords: ["정규화", "데이터 중복", "무결성", "원자값", "함수 종속성"]

# 채점 기준
grading_criteria:
  정확성:
    points: 40
    description: "내용의 정확성과 완전성"
    subcriteria:
      - "개념 정의의 정확성"
      - "예시의 적절성"
      - "핵심 키워드 포함 여부"
      
  논리성:
    points: 25
    description: "논리적 구성과 체계성"
    subcriteria:
      - "답변의 체계적 구성"
      - "논리적 연결성"
      - "순서의 적절성"
      
  명확성:
    points: 20
    description: "설명의 명확성과 이해도"
    subcriteria:
      - "용어 사용의 정확성"
      - "설명의 구체성"
      - "가독성"
      
  창의성:
    points: 10
    description: "창의적 사고와 독창성"
    subcriteria:
      - "독창적인 예시나 접근"
      - "추가적인 통찰"
      
  표현력:
    points: 5
    description: "문법과 표현"
    subcriteria:
      - "문법의 정확성"
      - "어휘 사용의 적절성"

# 등급 기준
grade_scale:
  "A+": 95
  "A": 90
  "B+": 85
  "B": 80
  "C+": 75
  "C": 70
  "D+": 65
  "D": 60
  "F": 0

# 채점 옵션
grading_options:
  strict_mode: false  # 엄격한 채점 모드
  partial_credit: true  # 부분 점수 허용
  keyword_bonus: true  # 키워드 보너스 점수
  creativity_bonus: 5  # 창의성 보너스 최대 점수
