# docker/docker-compose.worker.yaml
version: '3.8'

services:
  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-ml_serving}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  worker:
    build:
      context: ..
      dockerfile: docker/worker.Dockerfile
    volumes:
      - ../uploads:/app/uploads
      - ../logs:/app/logs
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-ml_serving}
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY:-your-secret-key}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - UPLOAD_DIR=/app/uploads
      - MODEL_DIR=/app/uploads/models
      - MAX_UPLOAD_SIZE=104857600
    depends_on:
      - redis
      - postgres
    command: celery -A worker.celery_app worker --loglevel=info --concurrency=1

  beat:
    build:
      context: ..
      dockerfile: docker/worker.Dockerfile
    volumes:
      - ../uploads:/app/uploads
      - ../logs:/app/logs
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-ml_serving}
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY:-your-secret-key}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - UPLOAD_DIR=/app/uploads
      - MODEL_DIR=/app/uploads/models
      - MAX_UPLOAD_SIZE=104857600
    depends_on:
      - redis
      - postgres
    command: celery -A worker.celery_app beat --loglevel=info

volumes:
  redis_data:
  postgres_data:
